site_name: Coding for science
theme:
  name: 'material'
remote_branch: 'master'

pages:
    - Home: 'index.md'
    - Setting a coding env: 
      - 'On Windows': 'set_env/env_windows.md'
      - 'On Linux': 'set_env/env_linux.md'
      - 'On Mac': 'set_env/env_mac.md'
    - Developping code: 
      - 'The Jupyter ecosystem': 'dev/jupyter.md'
      - 'Version Control with git': 'dev/git.md'
      - 'Collaboration with Github': 'dev/github.md'
      - 'Access to a remote server': 'dev/remote.md'
      - 'Code testing': 'dev/testing.md'
    - Publishing code:
      - 'Make a package': 'publish/package.md'
      - 'Legal issues (licensing...)': 'publish/legal_issues.md'
      - 'Reproducible examples': 'publish/binder.md'
      - 'Documenting': 'publish/documenting.md'
      - 'Build a open source project': 'publish/collaboration.md'
    - About: about.md
